"""
test_generator — Phase 2.

Real version: an LLM call with project context (skills/pom_builder,
skills/spec_writer, skills/locator_strategy, skills/assertion_author) that
writes a new test file from the structured spec.

Demo version: templated Python string generation, no LLM call — but it
exposes `inject_violation` so you can force a bad generation and watch
Phase 4 (semantic gate) catch it. This is the thing to run twice: once
clean, once with a violation, to see both branches of ADR-014's gates.
"""
from __future__ import annotations

from pathlib import Path

from ..hooks.trace_hook import log_event

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "src" / "tests" / "test_tenant_onboarding_generated.py"

CLEAN_TEMPLATE = '''"""
GENERATED by test_generator agent for ticket {ticket_id}.
Applies skills: pom_builder, locator_strategy, assertion_author.
"""
from src.pages.onboarding_page import OnboardingPage


def test_finish_disabled_before_plan_selection(page):
    onboarding = OnboardingPage(page)
    onboarding.goto("/onboarding/wizard")

    assert onboarding.is_finish_enabled() is False, (
        "AC-1 violated: Finish must stay disabled until benefits_selected"
    )
'''

# Same seeded violation as golden_dataset/dirty/dirty_01.py — used to prove
# the semantic gate actually fires on real pipeline output, not just on the
# calibration file sitting untouched in golden_dataset/.
VIOLATION_TEMPLATE = '''"""
GENERATED by test_generator agent for ticket {ticket_id}.
"""
import time

from src.pages.onboarding_page import OnboardingPage


def test_finish_disabled_before_plan_selection(page):
    onboarding = OnboardingPage(page)
    onboarding.goto("/onboarding/wizard")

    time.sleep(3)
    assert onboarding.page.url
'''


def run(spec: dict, inject_violation: bool = False) -> str:
    template = VIOLATION_TEMPLATE if inject_violation else CLEAN_TEMPLATE
    code = template.format(ticket_id=spec["ticket_id"])

    log_event("test_generator", "pre_tool_call", {
        "tool": "write_file",
        "path": str(OUTPUT_PATH.relative_to(REPO_ROOT)),
        "inject_violation": inject_violation,
    })
    OUTPUT_PATH.write_text(code)
    log_event("test_generator", "post_tool_call", {"bytes_written": len(code)})

    return str(OUTPUT_PATH)
