import { type Locator, type Page } from '@playwright/test';
import { BasePage } from './base-page';

/**
 * OnboardingPage — generated by test-generator following the pom-builder
 * and locator-strategy skills.
 *
 * Deliberate design choice, per pom-builder skill rule 6: locators are
 * exposed as public `readonly Locator` fields, not wrapped in async
 * boolean-returning methods like `isFinishEnabled()`. A test asserts
 * directly on the Locator with Playwright's web-first assertions
 * (`await expect(page.finishButton).toBeEnabled()`), which auto-retries.
 * A method that awaits `.isEnabled()` internally and returns a plain
 * boolean throws that retry away — and, as it turns out, also hides the
 * pattern from ESLint: `playwright/prefer-web-first-assertions` only
 * matches a raw Playwright locator method call, not a call one level
 * behind your own method. Wrapping state in a boolean method doesn't just
 * lose auto-retry, it defeats the linter too.
 */
export class OnboardingPage extends BasePage {
  readonly benefitPlanDropdown: Locator = this.page.getByTestId('benefit-plan-select');
  readonly finishButton: Locator = this.page.getByRole('button', { name: 'Finish' });
  readonly planOptions: Locator = this.page.getByTestId('plan-option');
  private readonly planOption = (name: string) => this.page.getByTestId(`plan-option-${name}`);

  constructor(page: Page) {
    super(page);
  }

  async selectBenefitPlan(planName: string): Promise<this> {
    await this.clickWhenVisible(this.benefitPlanDropdown);
    await this.clickWhenVisible(this.planOption(planName));
    return this;
  }

  async clickFinish(): Promise<this> {
    await this.clickWhenVisible(this.finishButton);
    return this;
  }

  async openPlanDropdown(): Promise<this> {
    await this.clickWhenVisible(this.benefitPlanDropdown);
    return this;
  }
}
