import { type Page } from '@playwright/test';
import { BasePage } from './base-page';

/**
 * OnboardingPage — generated by the test-generator agent following the
 * pom-builder and locator-strategy skills.
 *
 * Locators use data-testid first (locator-strategy skill, priority order).
 * Every public method is business language, not raw Playwright calls
 * (pom-builder skill, rule 3).
 */
export class OnboardingPage extends BasePage {
  private readonly benefitPlanDropdown = this.page.getByTestId('benefit-plan-select');
  private readonly finishButton = this.page.getByRole('button', { name: 'Finish' });
  private planOption = (name: string) => this.page.getByTestId(`plan-option-${name}`);

  constructor(page: Page) {
    super(page);
  }

  async selectBenefitPlan(planName: string): Promise<this> {
    await this.clickWhenVisible(this.benefitPlanDropdown);
    await this.clickWhenVisible(this.planOption(planName));
    return this;
  }

  async clickFinish(): Promise<this> {
    await this.clickWhenVisible(this.finishButton);
    return this;
  }

  async isFinishEnabled(): Promise<boolean> {
    return this.finishButton.isEnabled();
  }

  async visiblePlanOptions(): Promise<string[]> {
    // used by the tenant-isolation test — rule 2 in wiki/business_domain.md
    await this.clickWhenVisible(this.benefitPlanDropdown);
    return this.page.getByTestId('plan-option').allInnerTexts();
  }
}
