"""
OnboardingPage — generated by the test-generator agent following the
pom_builder and locator_strategy skills.

Locators use data-testid first (locator_strategy skill, priority order).
Every public method is business language, not raw Playwright calls
(pom_builder skill, rule 3).
"""
from __future__ import annotations

from playwright.sync_api import Page

from .base_page import BasePage


class OnboardingPage(BasePage):
    def __init__(self, page: Page):
        super().__init__(page)
        self._benefit_plan_dropdown = page.get_by_test_id("benefit-plan-select")
        self._finish_button = page.get_by_role("button", name="Finish")
        self._plan_option = lambda name: page.get_by_test_id(f"plan-option-{name}")

    def select_benefit_plan(self, plan_name: str) -> "OnboardingPage":
        self._click_when_visible(self._benefit_plan_dropdown)
        self._click_when_visible(self._plan_option(plan_name))
        return self

    def click_finish(self) -> "OnboardingPage":
        self._click_when_visible(self._finish_button)
        return self

    def is_finish_enabled(self) -> bool:
        return self._finish_button.is_enabled()

    def visible_plan_options(self) -> list[str]:
        # used by the tenant-isolation test — rule 2 in wiki/business_domain.md
        self._click_when_visible(self._benefit_plan_dropdown)
        options = self.page.get_by_test_id("plan-option").all_inner_texts()
        return options
